# Site
name: "danisnowman"
title: "danisnowman"
description: "My name is Daniel Hernández and this is my blog"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: /home
google_analytics: 'UA-59915356-6'
disqus: 'demowebsite'
mailchimp-list: 'http://eepurl.com/g1YAVP'
include: ["_pages"]
permalink: /:title/
email: danielernesto@ufm.edu

# Authors
authors:
  dani:
    name: Daniel Hernández
    display_name: Daniel
    gravatar: 43061e53ed43a9387e0298da951deb11
    email: danisnowman@gmail.com
    web: https://danisnowman.now.sh
    twitter: https://twitter.com/snowminal
    instagram: https://instagram.com/danisnowman
    description: "I am a Computer Science major who is passionate about Jesus and I really like reading and tech."
  john:
    name: John
    display_name: John    
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: rouge
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : false



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enable"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
